import type { NextPage } from 'next';
import Head from 'next/head';
import { Token } from '../components/Token';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>3D Token Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to 3D Token Test</h1>
        <Token />
      </main>
    </div>
  );
};

export default Home;
